name: swastika26
region: blr1
services:
- name: web
  image:
    registry_type: DOCR
    repository: swastika26
    tag: latest
  build_command: npm install && npm run build
  run_command: npm run start
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
  envs:
  - key: DATABASE_URL
    type: SECRET
  - key: NODE_ENV
    value: production
  - key: HOSTNAME
    value: "0.0.0.0"
  - key: PORT
    value: "8080"
